### ISSUE TITLE
Code implementation for hyperbolic layers

### ISSUE THREAD

**Issue by guikunchen** [cvlab-columbia/hyperfuture#5]
The released hyperbolic modules [performs exp_0 after linear layer in Euclidean space](https://github.com/cvlab-columbia/hyperfuture/blob/8c02b133754ffa95cb1c9c0c70aeb98078787a8a/backbone/hyrnn_nets.py#L26), which may be contrary to the illustration of Figure 3.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/45501633/223310588-93c36454-8073-437b-98b4-74f3bc35993e.png">
It seems that there is not hyperbolic linear layes after $exp_0$, i.e., [the h module in the left of exp_0](https://github.com/cvlab-columbia/hyperfuture/blob/main/models.py#L203).

**Comment by surisdi** [comment]
Hi,

The line of code you link is not the full linear layer. The full linear layer is the whole `mobius_linear` operation. The practical way of doing the linear layer operation in hyperbolic space, as explained [in this paper](https://proceedings.neurips.cc/paper/2018/file/dbab2adc8f9d078009ee3fa810bea142-Paper.pdf) (Section 3.2) is to do a logarithmic mapping to the tangent space (Euclidean space), then performing a matrix multiplication in that space (line of code you link to -- which doesn't contain the bias addition), followed by an exponential mapping to the hyperbolic space again, and finally an addition of the bias (in hyperbolic space). That is the complete "linear layer".

When the input happens to already be in the tangent (Euclidean) space, the first logarithmic mapping is not necessary. You can understand it as first performing the exponential mapping in the figure, and then a logarithmic mapping to invert it.

Let me know if you have any more questions.
